[mgr]
cwd               = { fg = "#FFFFFF", bg = "#FFA5D2", bold = true, underline = true }
border_style      = { fg = "#FFDCFF", bold = true }
find_keyword      = { fg = "#FFFFFF", bg = "#FFC855", bold = true, underline = true }

marker_selected   = { bg = "#9BFF78" }
marker_copied     = { bg = "#F2B90F" }
marker_cut        = { bg = "#FF8A8A" }
count_selected    = { fg = "#000000", bg = "#9BFF78", bold = true }
count_copied      = { fg = "#000000", bg = "#F2B90F", bold = true }
count_cut         = { fg = "#000000", bg = "#FF8A8A", bold = true }

[tabs]
active            = { fg = "#000000", bg = "#FFB4FF", bold = true, underline = true }
inactive          = { fg = "#FFB4FF", bg = "#646464" }
sep_inner         = { open = "|", close = "|" }

[mode]
normal_main       = { fg = "#1F1B24", bg = "#F8BBD0" }
normal_alt        = { fg = "#FCE4EC", bg = "#2C2533" }

select_main       = { fg = "#FFFFFF", bg = "#EC407A" }
select_alt        = { fg = "#1F1B24", bg = "#F48FB1" }

unset_main        = { fg = "#B39DDB", bg = "#1F1B24" }
unset_alt         = { fg = "#CE93D8", bg = "#2C2533" }

[status]
overall           = { fg = "#E1E1E1", bg = "#483748" }

perm_type         = { fg = "#64DCFF" }
perm_read         = { fg = "#FFFF64" }
perm_write        = { fg = "#FF80AB" }
perm_exec         = { fg = "#78FF64" }
perm_sep          = { fg = "#B39DDB" }

progress_label    = { fg = "#FCE4EC" }
progress_normal   = { fg = "#F48FB1" }
progress_error    = { fg = "#F44336" }

[which]
cols      = 2
separator = " âœ¿  "

mask              = { fg = "#F8BBD0", bg = "#1F1B24" }
cand              = { fg = "#EC407A", bold = true }
rest              = { fg = "#F48FB1" }
desc              = { fg = "#DCC8FF" }
separator_style   = { fg = "#AD1457" }

[confirm]
btn_labels = [" [Y]es ðŸŒ¸ ", " [N]o ðŸŒ‘ "]

border            = { fg = "#FFDCFF", bold = true }
title             = { fg = "#FFA5E6", bold = true }
content           = { fg = "#FFDCF5" }
list              = { fg = "#F096FF" }
btn_yes           = { fg = "#1F1B24", bg = "#F48FB1", bold = true }
btn_no            = { fg = "#FFFFFF", bg = "#AD1457" }

[spot]
border            = { fg = "#FFDCFF", bold = true }
title             = { fg = "#FFA5E6", bold = true }
tbl_col           = { fg = "#FFDCF5" }
tbl_cell          = { fg = "#000000", bg = "#F096FF", bold = true }

[notify]
title_info        = { fg = "#64DCFF", bold = true }
title_warning     = { fg = "#FFFF64", bold = true }
title_error       = { fg = "#FF80AB", bold = true }

[pick]
border            = { fg = "#FFA5E6", bold = true }
active            = { fg = "#000000", bg = "#FFA0D8", bold = true }
inactive          = { fg = "#FFDCF5" }

[input]
border            = { fg= "#FFDCFF", bold = true }