[app]
overall           = { bg = "#2A1E24" }

[mgr]
cwd               = { fg = "#FFFFFF", bg = "#FFA5D2", bold = true, italics = true }
border_style      = { fg = "#FFDCFF", bold = true }
find_keyword      = { fg = "#FFFFFF", bg = "#FFC855", bold = true, underline = true }
hovered           = { fg = "black", bg = "#FFA0D8", bold = true }
preview_hovered   = { fg = "#FFDCF5" }

#marker_selected   = { bg = "#9BFF78" }
#marker_copied     = { bg = "#F2B90F" }
#marker_cut        = { bg = "#FF8A8A" }
#count_selected    = { fg = "#000000", bg = "#9BFF78", bold = true }
#count_copied      = { fg = "#000000", bg = "#F2B90F", bold = true }
#count_cut         = { fg = "#000000", bg = "#FF8A8A", bold = true }
marker_selected    = { fg = "white", bg = "green", bold = true }
marker_copied      = { fg = "white", bg = "yellow", bold = true }
marker_cut         = { fg = "white", bg = "red", bold = true }
count_selected    = { fg = "white", bg = "green", bold = true }
count_copied      = { fg = "white", bg = "yellow", bold = true }
count_cut         = { fg = "white", bg = "red", bold = true }

[indicator]
parent            = { fg = "#3A2420", bg = "#FFA0D7", bold = true }
current           = { fg = "#4B2E2A", bg = "#FFC8D7", bold = true }
preview           = { fg = "#52352C", bg = "#FFE8D1", bold = true }
padding           = { open = "ÓÇ∂", close = "ÓÇ¥" }


[tabs]
active            = { fg = "#000000", bg = "#FFB4FF", bold = true, underline = true }
inactive          = { fg = "#FFB4FF", bg = "#646464" }
sep_inner         = { open = "|", close = "|" }

[mode]
normal_main       = { fg = "#1F1B24", bg = "#F8BBD0" }
normal_alt        = { fg = "#FCE4EC", bg = "#2C2533" }

select_main       = { fg = "#FFFFFF", bg = "#EC407A" }
select_alt        = { fg = "#1F1B24", bg = "#F48FB1" }

unset_main        = { fg = "#B39DDB", bg = "#1F1B24" }
unset_alt         = { fg = "#CE93D8", bg = "#2C2533" }

[status]
overall           = { fg = "#E1E1E1", bg = "#483748" }

#perm_type         = { fg = "#64DCFF" }
#perm_read         = { fg = "#FFFF64" }
#perm_write        = { fg = "#FF80AB" }
#perm_exec         = { fg = "#78FF64" }
#perm_sep          = { fg = "#B39DDB" }
perm_type         = { fg = "blue" }
perm_read         = { fg = "yellow" }
perm_write        = { fg = "red" }
perm_exec         = { fg = "green" }
perm_sep          = { fg = "magenta" }

progress_label    = { fg = "#FCE4EC" }
progress_normal   = { fg = "#F48FB1" }
progress_error    = { fg = "#F44336" }

[which]
cols              = 2
separator         = " ‚úø  "
mask              = { fg = "#F8BBD0", bg = "#1F1B24" }
cand              = { fg = "#EC407A", bold = true }
rest              = { fg = "#F48FB1" }
desc              = { fg = "#DCC8FF" }
separator_style   = { fg = "#AD1457" }

[confirm]
btn_labels        = [" [Y]es üå∏ ", " [N]o üåë "]
border            = { fg = "#FFDCFF", bold = true }
title             = { fg = "#FF5078", bold = true }
content           = { fg = "#FFDCF5" }
list              = { fg = "#F096FF" }
btn_yes           = { fg = "#1F1B24", bg = "#F48FB1", bold = true }
btn_no            = { fg = "#FFFFFF", bg = "#AD1457" }

[spot]
border            = { fg = "#FFDCFF", bold = true }
title             = { fg = "#FFA5E6", bold = true }
tbl_col           = { fg = "#FFDCF5" }
tbl_cell          = { fg = "#000000", bg = "#F096FF", bold = true }

[notify]
title_info        = { fg = "#64DCFF", bold = true }
title_warning     = { fg = "#FFFF64", bold = true }
title_error       = { fg = "#FF80AB", bold = true }

[pick]
border            = { fg = "#FFA5E6", bold = true }
active            = { fg = "#000000", bg = "#FFA0D8", bold = true }
inactive          = { fg = "#FFDCF5" }

[help]
on                = { fg = "#64DCFF", bold = true }
run               = { fg = "#FF5078" }
desc              = { fg = "#FFDCF5", bold = true }
hovered           = { reversed = true, bold = true }
footer            = { fg = "#E1E1E1", bg = "#483748", bold = true, italic = true }
icon_info         = "üå∏"
icon_warn         = "‚ö†Ô∏è"
icon_error        = "üíî"

[input]
border            = { fg = "#FFDCFF", bold = true }
title             = { fg = "#FFA5E6", bold = true }
value             = { fg = "#FFDCF5" }
selected          = { fg = "#000000", bg = "#FFA0D8" }

[cmp]
border            = { fg = "#FFDCFF", bold = true }
active            = { fg = "#000000", bg = "#FFA0D8", bold = true }
inactive          = { fg = "#FFDCF5" }
icon_file         = "ÔÖõ"
icon_folder       = "Û∞ù∞"
icon_command      = "Ôíµ"

[tasks]
border            = { fg = "#FFDCFF", bold = true }
title             = { fg = "#FFA5E6", bold = true }
hovered           = { fg = "#000000", bg = "#FFA0D8", bold = true }

[icon]
prepend_dirs = [
  { name = "Downloads",           text = "Û∞âç",     fg = "#78FF64" },
  { name = "Desktop",             text = "Û∞áÑ",     fg = "cyan"    },
  { name = ".config",             text = "Óóº",     fg = "#A56E00" },
  { name = ".cargo",              text = "Û±òó",     fg = "#BE410E" },
  { name = ".cache",              text = "Û∞É®",     fg = "#B9FF78" },
  { name = ".local",              text = "Û±Çµ",     fg = "#64EBFF" },
  { name = ".git",                text = "Óóª",     fg = "#F1502F" },
  { name = ".npm",                text = "Óó∫",     fg = "#E64B4B" },
]

prepend_exts = [
  { name = "mp3",                 text = "Ôáá",     fg = "#D764FF" },
  { name = "wav",                 text = "Ôáá",     fg = "#D764FF" },
  { name = "m4a",                 text = "Ôáá",     fg = "#D764FF" },
  { name = "aac",                 text = "Ôáá",     fg = "#D764FF" },
  { name = "flac",                text = "Ôáá",     fg = "#D764FF" },
  { name = "aif",                 text = "Ôáá",     fg = "#D764FF" },
  { name = "aiff",                text = "Ôáá",     fg = "#D764FF" },
  { name = "ogg",                 text = "Ôáá",     fg = "#D764FF" },

  { name = "jpg",                 text = "ÔÄæ",     fg = "#4BFF4B" },
  { name = "jpeg",                text = "ÔÄæ",     fg = "#4BFF4B" },
  { name = "jfif",                text = "ÔÄæ",     fg = "#4BFF4B" },
  { name = "png",                 text = "ÔÄæ",     fg = "#4BFF4B" },
  { name = "gif",                 text = "ÔÄæ",     fg = "#4BFF4B" },
  { name = "tif",                 text = "ÔÄæ",     fg = "#4BFF4B" },
  { name = "tiff",                text = "ÔÄæ",     fg = "#4BFF4B" },
  { name = "webp",                text = "ÔÄæ",     fg = "#4BFF4B" },
  { name = "heic",                text = "ÔÄæ",     fg = "#4BFF4B" },
  { name = "svg",                 text = "ÔÄæ",     fg = "#4BFF4B" },
  { name = "eps",                 text = "ÔÄæ",     fg = "#4BFF4B" },

  { name = "mp4",                 text = "Ôî¨",     fg = "#E150FF" },
  { name = "mov",                 text = "Ôî¨",     fg = "#E150FF" },
  { name = "avi",                 text = "Ôî¨",     fg = "#E150FF" },
  { name = "mkv",                 text = "Ôî¨",     fg = "#E150FF" },
  { name = "wmv",                 text = "Ôî¨",     fg = "#E150FF" },

  { name = "pdf",                 text = "ÔáÅ",     fg = "#FF0000" },
  { name = "docx",                text = "Óö•",     fg = "#185ABD" },
  { name = "pptx",                text = "Û±éê",     fg = "#D24726" },
  { name = "xlsx",                text = "Û±éè",     fg = "#217346" },
  { name = "psd",                 text = "Óû∏",     fg = "#31A8FF" },
  { name = "txt",                 text = "ÔÖú",     fg = "#D7D7D7" },

  { name = "conf",                text = "Óòï",     fg = "#FF5500" },
  { name = "ini",                 text = "Óòï",     fg = "#FF5500" },
]

prepend_conds = [
  { if = "hidden & !(dir)",       text = "Û∞ä†",     fg = "#A5A5A5" },
  { if = "dir",                   text = "Û∞âã",     fg = "#FF87E1" },
  { if = "!(dir | link)",         text = "ÔÖõ",     fg = "#FFFFFF" },

  { if = ".gitconfig",            text = "Û∞ä¢",     fg = "#F1502F" },
  { if = ".gitignore",            text = "Û∞ä¢",     fg = "#F1502F" },
  { if = ".gitattribute",         text = "Û∞ä¢",     fg = "#F1502F" },
  { if = ".gitmodules",           text = "Û∞ä¢",     fg = "#F1502F" },
  { if = ".gitkeep",              text = "Û∞ä¢",     fg = "#F1502F" },
  { if = ".gitreview",            text = "Û∞ä¢",     fg = "#F1502F" },
  { if = ".gitmessage",           text = "Û∞ä¢",     fg = "#F1502F" },
]
